# Generated by Django 5.0.4 on 2024-04-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lecturer'), (2, 'Student')], default=2),
        ),
    ]
